# Lab 3: Pandas & Data Preprocessing

In [2]:
import pandas as pd

In [3]:
ecommerce_data = {
'OrderID': [101, 102, 103, 104, 105, 106, 107],
'CustomerName': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
'Category': ['Electronics', 'Fashion', 'Electronics', 'Home', 'Fashion', 'Electronics', 'Home'],
'Amount': [200, 150, 300, 400, 250, 500, 350],
'Discount': [20, 10, 30, 50, 20, 60, 40],
'PurchaseDate': pd.to_datetime(['2023-11-20', '2023-11-21', '2023-11-22',
'2023-11-23', '2023-11-24', '2023-11-25', '2023-11-26']),
'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'Chicago','New York']
}

In [4]:
# Create the df from the given data: dict
df = pd.DataFrame(ecommerce_data)

1. What is the shape of the dataset?

In [6]:
print(f"Shape of given data: {df.shape}")
print(df.columns)

Shape of given data: (7, 7)
Index(['OrderID', 'CustomerName', 'Category', 'Amount', 'Discount',
       'PurchaseDate', 'City'],
      dtype='str')

In [15]:
print(df.head())

   OrderID CustomerName     Category  Amount  Discount PurchaseDate  \
0      101        Alice  Electronics     200        20   2023-11-20
1      102          Bob      Fashion     150        10   2023-11-21
2      103      Charlie  Electronics     300        30   2023-11-22
3      104        David         Home     400        50   2023-11-23
4      105          Eve      Fashion     250        20   2023-11-24

          City
0     New York
1  Los Angeles
2     New York
3      Chicago
4  Los Angeles

2. Are there any null values in the dataset?

In [13]:
print("Null values in dataset: ")
print(df.isna().sum())

Null values in dataset:
OrderID         0
CustomerName    0
Category        0
Amount          0
Discount        0
PurchaseDate    0
City            0
dtype: int64

3.Retrieve [Charlie Electronics 300] using loc and iloc

In [28]:
#using iloc
data_1 = df.iloc[2,[1,2,3]]
data_2 = df.loc[2, ["CustomerName", "Category", "Amount"]]
print("Retrieved using iloc: ")
print(data_1)
print("\nRetrieved using loc: ")
print(data_2)
#print(data.to_dict().values())

Retrieved using iloc:
CustomerName        Charlie
Category        Electronics
Amount                  300
Name: 2, dtype: object

Retrieved using loc:
CustomerName        Charlie
Category        Electronics
Amount                  300
Name: 2, dtype: object

4. Fetch rows for orders placed by customers from New York.

In [29]:
q_filter = df["City"] == "New York"
data = df[q_filter]
print(data)

   OrderID CustomerName     Category  Amount  Discount PurchaseDate      City
0      101        Alice  Electronics     200        20   2023-11-20  New York
2      103      Charlie  Electronics     300        30   2023-11-22  New York
6      107        Grace         Home     350        40   2023-11-26  New York

5. What is the average order amount? What is the total discount provided?

In [34]:
avg_order_amt = df["Amount"].mean()
total_discount = df["Discount"].sum()
print(f"Average order amount: {avg_order_amt:.2f}")
print(f"Total discount provided: {total_discount}")

Average order amount: 307.14
Total discount provided: 230

6. Sort the orders by Amount in descending order

In [35]:
df.sort_values(by="Amount")

,OrderID,CustomerName,Category,Amount,Discount,PurchaseDate,City
1,102,Bob,Fashion,150,10,2023-11-21,Los Angeles
0,101,Alice,Electronics,200,20,2023-11-20,New York
4,105,Eve,Fashion,250,20,2023-11-24,Los Angeles
2,103,Charlie,Electronics,300,30,2023-11-22,New York
6,107,Grace,Home,350,40,2023-11-26,New York
3,104,David,Home,400,50,2023-11-23,Chicago
5,106,Frank,Electronics,500,60,2023-11-25,Chicago

7. Display all orders where the Category is "Electronics" and the Amount is greater than 250.

In [40]:
q_filter = (df["Category"] == "Electronics") & (df["Amount"] > 250)
df[q_filter]

   OrderID CustomerName     Category  Amount  Discount PurchaseDate      City
2      103      Charlie  Electronics     300        30   2023-11-22  New York
5      106        Frank  Electronics     500        60   2023-11-25   Chicago